name: Test CI
on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - "main"

jobs:
  verify_pull_request:
    runs-on: ubuntu-latest
    container: 
      image: ubuntu:noble
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
      - name: Install project dependencies
        run: |
          source /opt/ros/jazzy/setup.bash
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y --rosdistro jazzy
        shell: bash
      - name: Build project
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build
        shell: bash
      - name: Test project
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon test
        shell: bash
