name: Save image as package
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'docker/**'

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build image
        run: |
          docker build ./docker/ --tag ghcr.io/kpi-rover/ci-ros-image:latest
      - name: Push the image
        run: |
          docker push ghcr.io/kpi-rover/ci-ros-image:latest
      - name: Logout from GitHub Container Registry
        run: |
          docker logout
